### ISSUE TITLE
What the best your programming language?

### ISSUE THREAD

**Issue by dikiaap** [cjpatoilo/ama#1]

**Comment by cjpatoilo** [comment]
Hi @dikiaap 

## Surely JavaScript, and he's awesome.

_"JavaScript is a lightweight, interpreted, programming language with first-class functions. Most well-known as the scripting language for Web pages, many non-browser environments use it such as Node.js and Apache CouchDB. JS is a prototype-based, multi-paradigm, dynamic scripting language, supporting object-oriented, imperative, and functional programming styles."_ - MDN

_"Always bet on JavaScript"_ - Brendan Eich

**reasons**
JavaScript can be the ideal language for those who want to learn to program. But why? Programming is hard. Start programming is even more difficult. Compilers, editors, IDEs and SDKs installation can become major barriers for beginners. In JavaScript, all this is minimized. VMs are ubiquitous in browsers, the editor can be a simple Notepad and the first run is allowed even in IE6 on the old computer in the public library. What you need to install? Absolutely nothing.

**advantages**
- Simplicity - JavaScript is relatively simple to learn and implement.
- Fast - Being client-side, JavaScript is very fast because any code functions can be run immediately.
- Versatility. JavaScript plays nicely with other languages and can be used in a huge variety of applications.
- Server Load - Being client-side reduces the demand on the website server.
- Full Stack - Run both client-side and server-side. 
- Isomorphic - The client-side and server-side share the same code.

**disadvantages**
- Reliance on End User - JavaScript is sometimes interpreted differently by different browsers. Whereas server-side scripts will always produce the same output, client-side scripts can be a little unpredictable. Don't be overly concerned by this though - as long as you test your script in all the major browsers you should be safe.
- Security - Because the code executes on the users' computer, in some cases it can be exploited for malicious purposes.

Surely there should be other disadvantages when compared with other languages, but now only remember these.

Thanks for asking @dikiaap
